import type { Metadata } from "next";
import StyledComponentsRegistry from "../lib/registry";
import { ThemesProvider } from "@/lib/themes";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
