import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <nav>
          <Link href="/">Home</Link>
          {' | '}
          <Link href="/contact">Contact</Link>
          {' | '}
          <Link href="/with-layout">With Nested Layout</Link>
          {' | '}
          <Link href="/dynamic-page-1">Dynamic Page 1</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
